"""Add creatorId field

Revision ID: 9f7caffc48fc
Revises: 82bab8395a0a
Create Date: 2023-04-16 22:23:40.642722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7caffc48fc'
down_revision = '82bab8395a0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('creator_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'creator_id')
    # ### end Alembic commands ###
